<?php

use App\Http\Controllers\Api\V1\AccountContextController;
use App\Http\Controllers\Api\V1\ApplicationDirectoryController;
use App\Http\Controllers\Api\V1\CommerceController;
use App\Http\Controllers\Api\V1\ContextualAccessController;
use App\Http\Controllers\Api\V1\EmployerController;
use App\Http\Controllers\Api\V1\EstablishmentController;
use App\Http\Controllers\Api\V1\ItemController;
use App\Http\Controllers\Api\V1\MetricsController;
use App\Http\Controllers\Api\V1\PlatOrderController;
use App\Http\Controllers\Api\V1\PlatOrderingSettingsController;
use App\Http\Controllers\Api\V1\PlatPaymentController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1/apps/{application}')->middleware('app.context')->group(function () {
    Route::get('/directory', [ApplicationDirectoryController::class, 'index']);
    Route::get('/establishments', [EstablishmentController::class, 'index']);
    Route::get('/establishments/{slug}', [EstablishmentController::class, 'show']);
    Route::get('/catalog/{establishmentSlug}', [ItemController::class, 'catalog']);
    Route::get('/items', [ItemController::class, 'index']);
    Route::get('/commerce/catalog/{slug}', [CommerceController::class, 'catalog']);
    Route::post('/commerce/payments/mercadopago/webhook', [CommerceController::class, 'mercadoPagoWebhook'])->middleware('throttle:120,1');
    Route::post('/commerce/payments/{provider}/webhook', [CommerceController::class, 'paymentWebhook'])->where('provider', '[a-z0-9_-]+')->middleware('throttle:120,1');
    Route::get('/establishments/{slug}/ordering', [PlatOrderController::class, 'ordering']);
    Route::post('/payments/mercadopago/webhook', [PlatOrderController::class, 'mercadoPagoWebhook'])->middleware('throttle:120,1');

    Route::middleware(['auth:api', 'token.version'])->group(function () {
        Route::get('/me', [AccountContextController::class, 'show']);
        Route::get('/me/relationships', [ContextualAccessController::class, 'relationships']);
        Route::post('/resources/{resourceRef}/authorize', [ContextualAccessController::class, 'authorizeResource'])->whereUuid('resourceRef');
        Route::get('/me/establishments', [EstablishmentController::class, 'mine']);
        Route::get('/directory/companies', [ApplicationDirectoryController::class, 'companies']);
        Route::post('/directory/companies/{sourceId}/activate', [ApplicationDirectoryController::class, 'activateCompany'])->whereNumber('sourceId');
        Route::delete('/directory/companies/{sourceId}/activate', [ApplicationDirectoryController::class, 'deactivateCompany'])->whereNumber('sourceId');
        Route::post('/establishments', [EstablishmentController::class, 'store']);
        Route::patch('/establishments/{establishment}', [EstablishmentController::class, 'update']);
        Route::delete('/establishments/{establishment}', [EstablishmentController::class, 'destroy']);
        Route::get('/establishments/{establishment}/metrics', [MetricsController::class, 'establishment']);
        Route::get('/establishments/{establishment}/items', [ItemController::class, 'mine']);
        Route::post('/items', [ItemController::class, 'store']);
        Route::patch('/items/{item}', [ItemController::class, 'update']);
        Route::delete('/items/{item}', [ItemController::class, 'destroy']);
        Route::get('/items/{item}/metrics', [MetricsController::class, 'item']);
        Route::get('/establishments/{establishment}/employers', [EmployerController::class, 'index']);
        Route::post('/employers', [EmployerController::class, 'store']);
        Route::delete('/employers/{employer}', [EmployerController::class, 'destroy']);
        Route::get('/employers/{employer}/items', [EmployerController::class, 'items']);
        Route::put('/employers/{employer}/items', [EmployerController::class, 'syncItems']);
        Route::get('/employers/{employer}/metrics', [EmployerController::class, 'metrics']);
        Route::post('/commerce/orders', [CommerceController::class, 'checkout'])->middleware('throttle:30,1');
        Route::get('/commerce/orders/mine', [CommerceController::class, 'myOrders']);
        Route::get('/commerce/orders/{publicId}', [CommerceController::class, 'show']);
        Route::get('/commerce/orders/{publicId}/payment', [CommerceController::class, 'payment']);
        Route::post('/commerce/orders/{publicId}/payment', [CommerceController::class, 'retryPayment'])->middleware('throttle:20,1');
        Route::get('/commerce/establishments/{establishment}/orders', [CommerceController::class, 'establishmentOrders'])->whereNumber('establishment');
        Route::patch('/commerce/orders/{publicId}/status', [CommerceController::class, 'updateStatus']);
        Route::post('/commerce/orders/{publicId}/fulfillment/verify', [CommerceController::class, 'verifyFulfillment'])->middleware('throttle:60,1');
        Route::get('/commerce/orders/{publicId}/fulfillment', [CommerceController::class, 'verifyFulfillment'])->middleware('throttle:60,1');
        Route::post('/commerce/orders/{publicId}/redeem', [CommerceController::class, 'redeem'])->middleware('throttle:30,1');
        Route::post('/orders', [PlatOrderController::class, 'checkout'])->middleware('throttle:30,1');
        Route::get('/me/orders', [PlatOrderController::class, 'myOrders']);
        Route::get('/me/orders/{order}', [PlatOrderController::class, 'myOrder'])->whereNumber('order');
        Route::get('/me/orders/{order}/payment', [PlatPaymentController::class, 'show'])->whereNumber('order');
        Route::get('/establishments/{establishment}/orders', [PlatOrderController::class, 'establishmentOrders'])->whereNumber('establishment');
        Route::patch('/orders/{order}/status', [PlatOrderController::class, 'updateStatus'])->whereNumber('order');
        Route::get('/dashboard', [PlatOrderController::class, 'dashboard']);
        Route::get('/establishments/{establishment}/ordering-settings', [PlatOrderingSettingsController::class, 'show'])->whereNumber('establishment');
        Route::patch('/establishments/{establishment}/ordering-settings', [PlatOrderingSettingsController::class, 'update'])->whereNumber('establishment');
    });
});
