[program:petertecnet-scheduler]
process_name=%(program_name)s
command=/usr/bin/php /var/www/api.petertecnet.com.br/artisan schedule:work --no-interaction
directory=/var/www/api.petertecnet.com.br
user=www-data
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=10
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/petertecnet-scheduler.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
environment=APP_ENV="staging"
