[program:petertecnet-queue]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/nice -n 10 /usr/bin/php /var/www/api.petertecnet.com.br/artisan queue:work redis --sleep=1 --tries=3 --timeout=90 --max-jobs=500 --max-time=3600
numprocs=1
directory=/var/www/api.petertecnet.com.br
user=www-data
autostart=true
autorestart=true
startsecs=3
stopwaitsecs=100
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/petertecnet-queue.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
priority=20
