<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    protected $fillable = [
        'report_type',
        'period_start',
        'period_end',
        'cash_flow',
        'gross_profit',
        'net_profit',
        'total_expenses',
        'revenue_by_channel',
        'avg_service_time',
        'cancellation_rate',
        'peak_hours',
        'resource_utilization',
        'new_customers_count',
        'returning_customers_count',
        'avg_ticket_per_customer',
        'visit_frequency',
        'satisfaction_index',
        'stock_turnover',
        'reorder_alerts_count',
        'raw_material_cost',
        'individual_performance',
        'labor_efficiency',
        'commissions_and_bonuses',
        'campaign_roi',
        'promotion_conversion_rate',
        'lead_origin',
        'barbershop_completion_rate',
        'avg_service_time_barbershop',
        'restaurant_prep_time',
        'table_turnover_rate',
        'legal_cases_opened_count',
        'legal_cases_closed_count',
        'avg_legal_case_duration',
        'hospital_bed_occupancy_rate',
        'hospital_readmission_rate',
        'avg_hospital_stay_duration',
        'endpoint_usage',
        'error_rate',
        'avg_latency',
        'auth_login_attempts_count',
        'auth_login_failures_count',
    ];

    protected $casts = [
        'period_start' => 'datetime',
        'period_end' => 'datetime',
        'revenue_by_channel' => 'array',
        'peak_hours' => 'array',
        'individual_performance' => 'array',
        'lead_origin' => 'array',
        'endpoint_usage' => 'array',
        'satisfaction_index' => 'float',
        'cancellation_rate' => 'float',
        'resource_utilization' => 'float',
        'visit_frequency' => 'float',
        'avg_service_time' => 'float',
        'avg_ticket_per_customer' => 'float',
        'cash_flow' => 'decimal:2',
        'gross_profit' => 'decimal:2',
        'net_profit' => 'decimal:2',
        'total_expenses' => 'decimal:2',
        'raw_material_cost' => 'decimal:2',
        'labor_efficiency' => 'float',
        'commissions_and_bonuses' => 'decimal:2',
        'campaign_roi' => 'float',
        'promotion_conversion_rate' => 'float',
        'barbershop_completion_rate' => 'float',
        'avg_service_time_barbershop' => 'float',
        'restaurant_prep_time' => 'float',
        'table_turnover_rate' => 'float',
        'legal_cases_opened_count' => 'integer',
        'legal_cases_closed_count' => 'integer',
        'avg_legal_case_duration' => 'float',
        'hospital_bed_occupancy_rate' => 'float',
        'hospital_readmission_rate' => 'float',
        'avg_hospital_stay_duration' => 'float',
        'error_rate' => 'float',
        'avg_latency' => 'decimal:2',
        'auth_login_attempts_count' => 'integer',
        'auth_login_failures_count' => 'integer',
    ];
}
