<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SupportRequest extends Model
{
    use HasFactory;

    protected $fillable = [
        'application_id', 'user_id', 'category', 'priority', 'status', 'subject', 'description',
        'route', 'app_version', 'device', 'correlation_id', 'first_responded_at', 'resolved_at', 'metadata',
    ];

    protected $casts = [
        'metadata' => 'array',
        'first_responded_at' => 'datetime',
        'resolved_at' => 'datetime',
    ];

    public function application() { return $this->belongsTo(Application::class, 'application_id'); }
    public function user() { return $this->belongsTo(User::class); }

    /**
     * Correlated telemetry for this support request.
     *
     * correlation_id is generated by clients/gateways and is not globally unique,
     * therefore application_id is part of the correlation boundary. Keeping this
     * constraint here prevents support tooling from exposing telemetry from another
     * Peter Tecnet application that happens to reuse the same correlation id.
     */
    public function interactions()
    {
        return $this->hasMany(Interaction::class, 'correlation_id', 'correlation_id')
            ->where('app_id', $this->application_id);
    }
}
